apiVersion: v1
kind: Secret
metadata:
  name: neptune-mysql-secret
  namespace: neptune
  labels:
    app: neptune-mysql
    app.kubernetes.io/name: neptune-mysql
    app.kubernetes.io/component: database
type: Opaque
# 注意: 以下为 base64 编码，实际部署时请修改为安全密码
# echo -n '123456' | base64 -> MTIzNDU2
data:
  root-password: MTIzNDU2
  user-password: MTIzNDU2
