apisix:
  node_listen: 9080
  enable_admin: false
  enable_control: true
  control:
    ip: 0.0.0.0
    port: 9090
  proxy_mode: http

deployment:
  role: traditional
  role_traditional:
    config_provider: yaml
