apiVersion: v1
kind: Service
metadata:
  name: neptune-web
  labels:
    app: neptune-web
    app.kubernetes.io/name: neptune-web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "1.0.0"
spec:
  type: ClusterIP
  selector:
    app: neptune-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
